
editor:
  externalPlugins:
    footquote:
      resource: "EXT:lbo_footnote/Resources/Public/footquote/plugin.js"
  config:
    extraAllowedContent : "footquote(*)[*]; span(*)[*]; p(*)[*]; div(*)[*]; a(*)[*]"
    format_tags: "p;h2;h3;h4;h5;h6;footquote"
    format_footquote: { name: "Note de bas de page", element: 'footquote' }
    allowTags:
      - footquote

processing:
  allowTags:
    - footquote